;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;                                                                            ;
;                                  hw.inc                                    ;
;                      Hardware configuraiton symbols                        ;
;                                                                            ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; This file contains hardware configuration for the current project. 
; It is included by the main application file and other files.
; Modify as needed.

; local includes 
    .include "cc26x2r/gpt_reg.inc"


